// my-zero-omega-react/src/options/Options.tsx
import {
  FormEvent,
  useCallback,
  useEffect,
  useMemo,
  useState,
} from 'react';
import {
  AppState,
  AutoSwitchProfile,
  AutoSwitchRule,
  FixedProfile,
  FixedScheme,
  GetStateResponse,
  MSG,
  Profile,
  ProfileMap,
  ProfileType,
} from '../lib/constants';
import { send } from '../lib/rpc';

// -----------------------------------------------------------------------------
// Options page.
// Mirrors the vanilla options.js semantics, but leans on React's controlled
// inputs so we don't need a `collectForm()` step — the `editing` object is
// always the truth for what will be POSTed to SAVE_PROFILE.
// -----------------------------------------------------------------------------

// Built-ins first, then alphabetical by name.
function profileOrder(a: Profile, b: Profile): number {
  const abt = a.type.startsWith('builtin') ? 0 : 1;
  const bbt = b.type.startsWith('builtin') ? 0 : 1;
  if (abt !== bbt) return abt - bbt;
  return a.name.localeCompare(b.name);
}

// Same id shape as the vanilla version, so an existing chrome.storage.local
// blob from the original extension would still round-trip cleanly.
function uid(prefix: string): string {
  return `${prefix}_${Math.random().toString(36).slice(2, 8)}`;
}

function makeFixedProfile(): FixedProfile {
  return {
    id: uid('fixed'),
    name: 'New Proxy',
    type: ProfileType.FIXED,
    scheme: 'http',
    host: '',
    port: 8080,
    bypassList: ['<local>'],
  };
}

function makeAutoProfile(): AutoSwitchProfile {
  return {
    id: uid('auto'),
    name: 'Auto Switch',
    type: ProfileType.AUTO_SWITCH,
    defaultProfileId: 'direct',
    rules: [],
  };
}

function validate(p: Profile, profiles: ProfileMap): string | null {
  if (!p.name) return 'Name is required.';
  if (p.type === ProfileType.FIXED) {
    if (!p.host) return 'Host is required.';
    if (!(p.port >= 1 && p.port <= 65535)) return 'Port must be between 1 and 65535.';
  }
  if (p.type === ProfileType.AUTO_SWITCH) {
    if (!p.defaultProfileId) return 'Default profile is required.';
    if (!profiles[p.defaultProfileId]) return 'Default profile no longer exists.';
    for (const r of p.rules ?? []) {
      if (!r.pattern) return 'Rule pattern cannot be empty.';
      if (!profiles[r.profileId]) return `Rule targets a missing profile: ${r.profileId}`;
    }
  }
  return null;
}

// -----------------------------------------------------------------------------
// Editor message banner
// -----------------------------------------------------------------------------

type MsgKind = '' | 'ok' | 'error';
interface MsgState { text: string; kind: MsgKind }

const EMPTY_MSG: MsgState = { text: '', kind: '' };

// -----------------------------------------------------------------------------
// Root
// -----------------------------------------------------------------------------

export default function Options() {
  const [state, setState] = useState<AppState | null>(null);
  const [editing, setEditing] = useState<Profile | null>(null);
  const [msg, setMsg] = useState<MsgState>(EMPTY_MSG);

  const refresh = useCallback(async () => {
    const res = await send<GetStateResponse>({ type: MSG.GET_STATE });
    setState(res.state);
    // Re-sync editor with latest storage IF editor is not a draft. Drafts are
    // in-flight objects the user hasn't saved yet — never overwrite them.
    setEditing(prev => {
      if (!prev) return prev;
      const stored = res.state.profiles[prev.id];
      if (!stored) return prev; // draft or just-deleted profile
      return structuredClone(stored);
    });
  }, []);

  useEffect(() => { void refresh(); }, [refresh]);

  const startEditing = useCallback((profile: Profile) => {
    setEditing(structuredClone(profile));
    setMsg(EMPTY_MSG);
  }, []);

  const onSubmit = async (e: FormEvent<HTMLFormElement>): Promise<void> => {
    e.preventDefault();
    if (!editing || !state) return;
    const err = validate(editing, state.profiles);
    if (err) {
      setMsg({ text: err, kind: 'error' });
      return;
    }
    try {
      await send({ type: MSG.SAVE_PROFILE, profile: editing });
      setMsg({ text: 'Saved.', kind: 'ok' });
      await refresh();
    } catch (e2) {
      setMsg({ text: (e2 as Error).message, kind: 'error' });
    }
  };

  const onDelete = async (): Promise<void> => {
    if (!editing) return;
    if (!confirm(`Delete profile "${editing.name}"?`)) return;
    try {
      await send({ type: MSG.DELETE_PROFILE, profileId: editing.id });
      setEditing(null);
      setMsg(EMPTY_MSG);
      await refresh();
    } catch (e2) {
      setMsg({ text: (e2 as Error).message, kind: 'error' });
    }
  };

  if (!state) {
    return (
      <>
        <header><h1>My Zero Omega — Options</h1></header>
        <main>
          <aside className="sidebar" />
          <section className="editor"><div className="empty">Loading…</div></section>
        </main>
      </>
    );
  }

  const isDraft = editing !== null && !state.profiles[editing.id];

  return (
    <>
      <header><h1>My Zero Omega — Options</h1></header>
      <main>
        <Sidebar
          profiles={state.profiles}
          editingId={editing?.id}
          onNewFixed={() => startEditing(makeFixedProfile())}
          onNewAuto={() => startEditing(makeAutoProfile())}
          onPick={startEditing}
        />
        <section className="editor">
          {!editing && (
            <div className="empty">Pick a profile on the left, or create a new one.</div>
          )}
          {editing && (
            <Editor
              profile={editing}
              profiles={state.profiles}
              isDraft={isDraft}
              onChange={setEditing}
              onSubmit={onSubmit}
              onDelete={onDelete}
              msg={msg}
            />
          )}
        </section>
      </main>
    </>
  );
}

// -----------------------------------------------------------------------------
// Sidebar
// -----------------------------------------------------------------------------

interface SidebarProps {
  profiles:   ProfileMap;
  editingId:  string | undefined;
  onNewFixed: () => void;
  onNewAuto:  () => void;
  onPick:     (p: Profile) => void;
}

function Sidebar({ profiles, editingId, onNewFixed, onNewAuto, onPick }: SidebarProps) {
  const items = useMemo(
    () => Object.values(profiles).sort(profileOrder),
    [profiles]
  );

  return (
    <aside className="sidebar">
      <div className="toolbar">
        <button type="button" onClick={onNewFixed}>+ Fixed Proxy</button>
        <button type="button" onClick={onNewAuto}>+ Auto Switch</button>
      </div>
      <ul className="profile-list">
        {items.map(p => (
          <li
            key={p.id}
            className={`item${editingId === p.id ? ' selected' : ''}`}
            onClick={() => onPick(p)}
          >
            <span className={`tag tag-${p.type}`} />
            <span className="name">{p.name}</span>
          </li>
        ))}
      </ul>
    </aside>
  );
}

// -----------------------------------------------------------------------------
// Editor
// -----------------------------------------------------------------------------

interface EditorProps {
  profile:  Profile;
  profiles: ProfileMap;
  isDraft:  boolean;
  onChange: (next: Profile) => void;
  onSubmit: (e: FormEvent<HTMLFormElement>) => void;
  onDelete: () => void;
  msg:      MsgState;
}

function Editor({ profile, profiles, isDraft, onChange, onSubmit, onDelete, msg }: EditorProps) {
  const p = profile;
  const isBuiltin = p.type.startsWith('builtin');
  const isFixed   = p.type === ProfileType.FIXED;
  const isAuto    = p.type === ProfileType.AUTO_SWITCH;

  return (
    <form className="editor-form" autoComplete="off" onSubmit={onSubmit}>
      <div className="row">
        <label>Name</label>
        <input
          type="text"
          value={p.name}
          disabled={isBuiltin}
          required
          onChange={e => onChange({ ...p, name: e.target.value })}
        />
      </div>
      <div className="row">
        <label>Type</label>
        <input type="text" value={p.type} disabled />
      </div>

      {isFixed && (
        <FixedFields
          profile={p as FixedProfile}
          onPatch={patch => onChange({ ...(p as FixedProfile), ...patch })}
        />
      )}
      {isAuto && (
        <AutoFields
          profile={p as AutoSwitchProfile}
          profiles={profiles}
          onPatch={patch => onChange({ ...(p as AutoSwitchProfile), ...patch })}
        />
      )}

      <div className="actions">
        {!isBuiltin && <button type="submit" className="primary">Save</button>}
        {!isBuiltin && !isDraft && (
          <button type="button" className="btn-delete" onClick={onDelete}>Delete</button>
        )}
      </div>
      <div className={`msg ${msg.kind}`.trim()}>{msg.text}</div>
    </form>
  );
}

// -----------------------------------------------------------------------------
// Fixed Proxy fields
// -----------------------------------------------------------------------------

const FIXED_SCHEMES: FixedScheme[] = ['http', 'https', 'socks5', 'socks4'];

interface FixedFieldsProps {
  profile: FixedProfile;
  onPatch: (patch: Partial<FixedProfile>) => void;
}

function FixedFields({ profile, onPatch }: FixedFieldsProps) {
  const p = profile;
  // We split bypassList on every keystroke so the `editing` object always has
  // array form matching the storage schema.
  const bypassText = (p.bypassList ?? []).join('\n');

  return (
    <fieldset>
      <legend>Fixed Proxy</legend>
      <div className="row">
        <label>Scheme</label>
        <select
          value={p.scheme}
          onChange={e => onPatch({ scheme: e.target.value as FixedScheme })}
        >
          {FIXED_SCHEMES.map(s => <option key={s} value={s}>{s}</option>)}
        </select>
      </div>
      <div className="row">
        <label>Host</label>
        <input
          type="text"
          value={p.host}
          placeholder="127.0.0.1"
          required
          onChange={e => onPatch({ host: e.target.value })}
        />
      </div>
      <div className="row">
        <label>Port</label>
        <input
          type="number"
          min={1}
          max={65535}
          value={p.port}
          required
          onChange={e => onPatch({ port: Number(e.target.value) })}
        />
      </div>
      <div className="row">
        <label>
          Bypass List
          <span className="hint">one per line — e.g. &lt;local&gt;, *.internal, 192.168.0.0/16</span>
        </label>
        <textarea
          rows={4}
          value={bypassText}
          onChange={e => onPatch({
            bypassList: e.target.value.split('\n').map(s => s.trim()).filter(Boolean),
          })}
        />
      </div>
    </fieldset>
  );
}

// -----------------------------------------------------------------------------
// Auto Switch fields
// -----------------------------------------------------------------------------

interface AutoFieldsProps {
  profile:  AutoSwitchProfile;
  profiles: ProfileMap;
  onPatch:  (patch: Partial<AutoSwitchProfile>) => void;
}

function AutoFields({ profile, profiles, onPatch }: AutoFieldsProps) {
  const p = profile;

  // Only non-auto profiles can be a rule/default target — no auto→auto nesting.
  const targets = useMemo(
    () => Object.values(profiles)
      .filter(x => x.type !== ProfileType.AUTO_SWITCH)
      .sort(profileOrder),
    [profiles]
  );

  const firstNonAutoId = targets[0]?.id ?? 'direct';

  const addRule = (): void => {
    const next: AutoSwitchRule = {
      pattern: '*.example.com',
      profileId: firstNonAutoId,
      matchType: 'wildcard',
    };
    onPatch({ rules: [...(p.rules ?? []), next] });
  };

  const removeRule = (i: number): void => {
    onPatch({ rules: (p.rules ?? []).filter((_, idx) => idx !== i) });
  };

  const updateRule = (i: number, patch: Partial<AutoSwitchRule>): void => {
    onPatch({
      rules: (p.rules ?? []).map((r, idx) => idx === i ? { ...r, ...patch } : r),
    });
  };

  return (
    <fieldset>
      <legend>Auto Switch</legend>
      <div className="row">
        <label>
          Default profile
          <span className="hint">used when no rule matches</span>
        </label>
        <select
          value={p.defaultProfileId}
          onChange={e => onPatch({ defaultProfileId: e.target.value })}
        >
          {targets.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}
        </select>
      </div>
      <div className="row">
        <label>
          Rules
          <span className="hint">wildcard: * = any chars, ? = one char</span>
        </label>
        <div>
          <table className="rules">
            <thead>
              <tr><th>Pattern</th><th>Target Profile</th><th /></tr>
            </thead>
            <tbody>
              {(p.rules ?? []).map((r, i) => (
                <tr key={i}>
                  <td>
                    <input
                      type="text"
                      value={r.pattern}
                      placeholder="*.example.com"
                      onChange={e => updateRule(i, { pattern: e.target.value })}
                    />
                  </td>
                  <td>
                    <select
                      value={r.profileId}
                      onChange={e => updateRule(i, { profileId: e.target.value })}
                    >
                      {targets.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}
                    </select>
                  </td>
                  <td>
                    <button
                      type="button"
                      className="btn-remove-rule"
                      title="Remove rule"
                      onClick={() => removeRule(i)}
                    >
                      ×
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          <button type="button" className="btn-add-rule" onClick={addRule}>
            + Add rule
          </button>
        </div>
      </div>
    </fieldset>
  );
}

// my-zero-omega-vue3/src/options/Options.vue
<script setup>
// Root options view — mirrors the vanilla options.js semantics, but leans on
// Vue's v-model reactivity so we don't need a `collectForm()` step. The
// `editing` ref is always the exact payload we send to SAVE_PROFILE.

import { computed, onMounted, ref } from 'vue';
import { MSG } from '../lib/constants.js';
import { send } from '../lib/rpc.js';
import { makeAutoProfile, makeFixedProfile, profileOrder, validate } from './helpers.js';
import Sidebar from './Sidebar.vue';
import Editor from './Editor.vue';

const state = ref(null);
/** Currently-editing profile snapshot (never a direct storage reference). */
const editing = ref(null);
const msg = ref({ text: '', kind: '' });

const sortedProfiles = computed(() => {
  if (!state.value) return [];
  return Object.values(state.value.profiles).sort(profileOrder);
});

// A draft is an in-flight new profile the user hasn't saved yet.
const isDraft = computed(() =>
  !!editing.value && !state.value?.profiles[editing.value.id]
);

async function refresh() {
  const res = await send({ type: MSG.GET_STATE });
  state.value = res.state;
  // Re-sync editor with latest storage IF editor is not a draft. Drafts
  // are transient objects — never overwrite them from storage.
  if (editing.value && state.value.profiles[editing.value.id]) {
    editing.value = structuredClone(state.value.profiles[editing.value.id]);
  }
}

onMounted(refresh);

function startEditing(profile) {
  editing.value = structuredClone(profile);
  msg.value = { text: '', kind: '' };
}

function onNewFixed() { startEditing(makeFixedProfile()); }
function onNewAuto()  { startEditing(makeAutoProfile()); }

async function onSubmit() {
  const err = validate(editing.value, state.value.profiles);
  if (err) { msg.value = { text: err, kind: 'error' }; return; }
  try {
    await send({ type: MSG.SAVE_PROFILE, profile: editing.value });
    msg.value = { text: 'Saved.', kind: 'ok' };
    await refresh();
  } catch (e) {
    msg.value = { text: e.message, kind: 'error' };
  }
}

async function onDelete() {
  if (!confirm(`Delete profile "${editing.value.name}"?`)) return;
  try {
    await send({ type: MSG.DELETE_PROFILE, profileId: editing.value.id });
    editing.value = null;
    msg.value = { text: '', kind: '' };
    await refresh();
  } catch (e) {
    msg.value = { text: e.message, kind: 'error' };
  }
}
</script>

<template>
  <header><h1>My Zero Omega — Options</h1></header>
  <main>
    <Sidebar
      :profiles="sortedProfiles"
      :editing-id="editing?.id"
      @new-fixed="onNewFixed"
      @new-auto="onNewAuto"
      @pick="startEditing"
    />
    <section class="editor">
      <div v-if="!editing" class="empty">
        Pick a profile on the left, or create a new one.
      </div>
      <Editor
        v-else
        v-model:profile="editing"
        :profiles="state.profiles"
        :is-draft="isDraft"
        :msg="msg"
        @submit="onSubmit"
        @delete="onDelete"
      />
    </section>
  </main>
</template>
