// my-zero-omega-vue3/src/options/AutoFields.vue
<script setup>
// Auto-switch fieldset: default profile picker + rules table.

import { computed } from 'vue';
import { ProfileType } from '../lib/constants.js';
import { profileOrder } from './helpers.js';

const props = defineProps({
  profile: { type: Object, required: true },
  profiles: { type: Object, required: true },
});
const emit = defineEmits(['update:profile']);

// Only non-auto profiles can be a rule/default target — no auto→auto nesting.
const targets = computed(() =>
  Object.values(props.profiles)
    .filter(x => x.type !== ProfileType.AUTO_SWITCH)
    .sort(profileOrder)
);

const firstNonAutoId = computed(() => targets.value[0]?.id ?? 'direct');

function patch(update) {
  emit('update:profile', { ...props.profile, ...update });
}

const defaultProfileIdModel = computed({
  get: () => props.profile.defaultProfileId,
  set: v => patch({ defaultProfileId: v }),
});

function addRule() {
  patch({
    rules: [
      ...(props.profile.rules || []),
      { pattern: '*.example.com', profileId: firstNonAutoId.value, matchType: 'wildcard' },
    ],
  });
}

function removeRule(i) {
  patch({
    rules: (props.profile.rules || []).filter((_, idx) => idx !== i),
  });
}

function updateRule(i, key, value) {
  patch({
    rules: (props.profile.rules || []).map(
      (r, idx) => idx === i ? { ...r, [key]: value } : r
    ),
  });
}
</script>

<template>
  <fieldset>
    <legend>Auto Switch</legend>
    <div class="row">
      <label>
        Default profile
        <span class="hint">used when no rule matches</span>
      </label>
      <select v-model="defaultProfileIdModel">
        <option v-for="t in targets" :key="t.id" :value="t.id">{{ t.name }}</option>
      </select>
    </div>
    <div class="row">
      <label>
        Rules
        <span class="hint">wildcard: * = any chars, ? = one char</span>
      </label>
      <div>
        <table class="rules">
          <thead>
            <tr><th>Pattern</th><th>Target Profile</th><th /></tr>
          </thead>
          <tbody>
            <tr v-for="(r, i) in profile.rules || []" :key="i">
              <td>
                <input
                  type="text"
                  :value="r.pattern"
                  placeholder="*.example.com"
                  @input="updateRule(i, 'pattern', $event.target.value)"
                >
              </td>
              <td>
                <select
                  :value="r.profileId"
                  @change="updateRule(i, 'profileId', $event.target.value)"
                >
                  <option v-for="t in targets" :key="t.id" :value="t.id">{{ t.name }}</option>
                </select>
              </td>
              <td>
                <button
                  type="button"
                  class="btn-remove-rule"
                  title="Remove rule"
                  @click="removeRule(i)"
                >×</button>
              </td>
            </tr>
          </tbody>
        </table>
        <button type="button" class="btn-add-rule" @click="addRule">
          + Add rule
        </button>
      </div>
    </div>
  </fieldset>
</template>

// my-zero-omega-angular/src/options/auto-fields.component.ts
// Auto-switch fieldset: default profile picker + rules table.

import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  model,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  AutoSwitchProfile,
  AutoSwitchRule,
  Profile,
  ProfileMap,
  ProfileType,
} from '../lib/constants';
import { profileOrder } from './helpers';

@Component({
  selector: 'app-auto-fields',
  standalone: true,
  imports: [FormsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <fieldset>
      <legend>Auto Switch</legend>

      <div class="row">
        <label>
          Default profile
          <span class="hint">used when no rule matches</span>
        </label>
        <select
          [ngModel]="profile().defaultProfileId"
          (ngModelChange)="patch({ defaultProfileId: $event })"
        >
          @for (t of targets(); track t.id) {
            <option [value]="t.id">{{ t.name }}</option>
          }
        </select>
      </div>

      <div class="row">
        <label>
          Rules
          <span class="hint">wildcard: * = any chars, ? = one char</span>
        </label>
        <div>
          <table class="rules">
            <thead>
              <tr><th>Pattern</th><th>Target Profile</th><th></th></tr>
            </thead>
            <tbody>
              @for (r of profile().rules; track $index; let i = $index) {
                <tr>
                  <td>
                    <input
                      type="text"
                      placeholder="*.example.com"
                      [ngModel]="r.pattern"
                      (ngModelChange)="updateRule(i, { pattern: $event })"
                    >
                  </td>
                  <td>
                    <select
                      [ngModel]="r.profileId"
                      (ngModelChange)="updateRule(i, { profileId: $event })"
                    >
                      @for (t of targets(); track t.id) {
                        <option [value]="t.id">{{ t.name }}</option>
                      }
                    </select>
                  </td>
                  <td>
                    <button
                      type="button"
                      class="btn-remove-rule"
                      title="Remove rule"
                      (click)="removeRule(i)"
                    >×</button>
                  </td>
                </tr>
              }
            </tbody>
          </table>
          <button type="button" class="btn-add-rule" (click)="addRule()">
            + Add rule
          </button>
        </div>
      </div>
    </fieldset>
  `,
})
export class AutoFieldsComponent {
  readonly profile  = model.required<AutoSwitchProfile>();
  readonly profiles = input.required<ProfileMap>();

  // Only non-auto profiles can be a rule/default target — no auto→auto nesting.
  protected readonly targets = computed<Profile[]>(() =>
    Object.values(this.profiles())
      .filter(x => x.type !== ProfileType.AUTO_SWITCH)
      .sort(profileOrder)
  );

  private readonly firstNonAutoId = computed<string>(() =>
    this.targets()[0]?.id ?? 'direct'
  );

  protected patch(update: Partial<AutoSwitchProfile>): void {
    this.profile.update(p => ({ ...p, ...update }));
  }

  protected addRule(): void {
    const newRule: AutoSwitchRule = {
      pattern:   '*.example.com',
      profileId: this.firstNonAutoId(),
      matchType: 'wildcard',
    };
    this.patch({ rules: [...(this.profile().rules ?? []), newRule] });
  }

  protected removeRule(i: number): void {
    this.patch({
      rules: (this.profile().rules ?? []).filter((_, idx) => idx !== i),
    });
  }

  protected updateRule(i: number, patch: Partial<AutoSwitchRule>): void {
    this.patch({
      rules: (this.profile().rules ?? []).map(
        (r, idx) => idx === i ? { ...r, ...patch } : r
      ),
    });
  }
}
